[admiral]
{% if layout == "alt" %}
items = ["left", "space", "timeicon", "todo", "calendar",
		 "clock", "closeclick", "closeclick",
                 "wsfw", "wsbk", "workspaces",
		 "closeclick", "closeclick", "modes", "reset",
 		 "right", "reset", "volup", "voldn", "mute", "volume",
		 "closeclick", "closeclick", "closeclick",
		 "separator", "battery"]
{% else %}
items = ["left", "space", "greet", "modes", "reset", "center", "wsfw", "wsbk", "workspaces",
		 "closeclick", "closeclick",
		 "right", "reset", "volup", "voldn", "mute", "volume",
		 "closeclick", "closeclick", "closeclick",
		 "separator", "todo", "calendar",
		 "clock", "closeclick", "closeclick", "separator", "battery"]
{% endif %}

[workspaces]
path = "~/.config/lemonbar/workspace"

[modes]
path = "~/.config/lemonbar/modes"

[timeicon]
{% if not bitmap %}
path = "echo '  '"
{% else %}
path = "echo '  '"
{% endif %}
static = true

[clock]
# path = "date '+%a %d %b %H:%M:%S'"
path = "date '+%a %d %b %H:%M'"
reload = 1

[battery]
path = "~/.config/lemonbar/battery"
reload = 10

[volume]
path = "~/.config/lemonbar/soundstate"
reload = 0.1

[greet]
{% if bitmap %}
path = "echo '  fullsalvo'"
{% else %}
path = "echo ' fullsalvo'"
{% endif %}
static = true

# Clickable Regions
[todo]
path = "echo '%{A:~/.bin/todo:}'"
static = true

[calendar]
path = "echo '%{A3:notify-send \"Calendar\" \"`ncal -h`\":}'"
static = true

[nowplaying]
path = "echo '%{A:~/.bin/mpc-notify:}'"
static = true

[wsbk]
path = "echo '%{A5:~/.config/lemonbar/wsbk:}'"
static = true

[wsfw]
path = "echo '%{A4:~/.config/lemonbar/wsfw:}'"
static = true

[volup]
path = "echo '%{A4:~/.config/lemonbar/volup:}'"
static = true

[voldn]
path = "echo '%{A5:~/.config/lemonbar/voldn:}'"
static = true

[mute]
path = "echo '%{A3:~/.config/lemonbar/mute:}'"
static = true

[closeclick]
path = "echo '%{A}'"
static = true

# Used for formatting lemonbar
[left]
path = "echo '%{l}'"
static = true

[center]
path = "echo '%{c}'"
static = true

[right]
path = "echo '%{r}'"
static = true

[reset]
path = "echo '%{F-}'"
static = true

[separator]
path = "echo '  |  '"
static = true

[space]
path = "echo '  '"
static = true
